services:
  db:
    image: postgres:15
    container_name: DB
    volumes:
      - ~/.pg/pg_data/web:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build:
      context: .
    container_name: WEB
    image: web_fox4
    entrypoint: /web/start.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - static:/web/static
      - media:/web/media
    env_file:
      - .env

  nginx:
    image: jwilder/nginx-proxy
    container_name: NGINX_jwilder
    restart: always
    volumes:
      - ./nginx/default_location:/etc/nginx/conf.d/default.conf
      - static:/web/static
      - media:/web/media
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  acme_companion:
    image: nginxproxy/acme-companion
    container_name: ACME_companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - acme:/etc/acme.sh



volumes:
  static:
  media:
  certs:
  vhost:
  acme:

