services:
  db:
    image: postgres:15
    container_name: DB
    volumes:
      - ~/.pg/pg_data/web:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build:
      context: .
    container_name: WEB
    image: web_fox4
    entrypoint: /web/start.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - static:/web/static
    env_file:
      - .env

  nginx:
    image: nginx
    container_name: NGINX
    volumes:
      - ./nginx/nginx.conf:/etc/nginx.conf.d/default.conf
      - static:/web/static
    ports:
      - "80:80"
    depends_on:
      - web


volumes:
  static:

