services:
  db:
    image: postgres:15
    container_name: DB
    volumes:
      - ~/.pg/pg_data/web:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build:
      context: .
    container_name: WEB
    image: web_fox4
    entrypoint: /web/start.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - static:/web/static
    env_file:
      - .env

  nginx:
    image: nginx
    container_name: NGINX
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/web/static
      - media:/web/media
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot/ --email pyth44a@gmail.com --agree-tos --no-eff-email -d www.fox4.ru
    depends_on:
      - nginx



volumes:
  static:
  media:

