services:
  db:
    image: postgres:15
    container_name: DB
    volumes:
      - ~/.pg/pg_data/web:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build:
      context: .
    container_name: WEB
    image: web_fox4
    entrypoint: /web/start.sh
    depends_on:
      - db
    volumes:
      - static:/web/static
      - media:/web/media
    env_file:
      - .env

  nginx:
    build:
      context: ./nginx/
    container_name: NGINX
    volumes:
      - static:/web/static
      - media:/web/media
    ports:
      - "8080:80"
    depends_on:
      - web


volumes:
  static:
  media:

