# Generated by Django 4.2.7 on 2023-12-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='file',
            field=models.ImageField(upload_to='uploads_model'),
        ),
    ]
